[build]
  command = "npm run build"
  functions = "netlify/functions/"
  publish = "build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "@sparticuz/chromium"]

[build.environment]
  CI = "false"